# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 12
      - run: sudo npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

